### ISSUE TITLE
Update to Ghidra 9.0.1

### ISSUE THREAD

**Issue by jrmuizel** [kant2002/Ghidra#4]
Ghidra 9.0.1 has now been released it would be nice if the changes were merged in.

**Comment by kant2002** [comment]
Thanks for noticing new release, I have some ongoing work to properly decompose changes into individual commits for easier reviewing, so it make take time. Don't want to do dump of the current state and override changes.

**Comment by kant2002** [comment]
Most of work for Ghidra 9.0.1 is completed, so I have to again re-validate things and attempt to run local build. Images would be screwed, but I will fix that.
